In [ ]:
# numpy works with Dimensions data
# numpy means numerical data
# numpy is also called library works


In [10]:
#import the package
import numpy as np

In [3]:
x=[1,5,7,11,13]
print(x)
print(type(x))

[1, 5, 7, 11, 13]
<class 'list'>


In [4]:
y=(10,90,30,40,50)
print(y)
print(type(y))

(10, 90, 30, 40, 50)
<class 'tuple'>


In [5]:
z={25,45,67,200}
print(z)
print(type(z))

{200, 25, 67, 45}
<class 'set'>


In [6]:
a='satish'
print(a)
print(type(a))

satish
<class 'str'>


In [7]:
b={'course':['python','sql','powerBi'],'fee':[25000,20000,22000],'duration':['2Months','2.5Months','3Months']}
print(b)
print(type(b))

{'course': ['python', 'sql', 'powerBi'], 'fee': [25000, 20000, 22000], 'duration': ['2Months', '2.5Months', '3Months']}
<class 'dict'>


In [9]:
# array

int=np.array([10,40,80,100])
print(int)
print(type(int))

[ 10  40  80 100]
<class 'numpy.ndarray'>


In [10]:
a=np.array([10000,250.55,'python'])
print(a)
print(type(a))

['10000' '250.55' 'python']
<class 'numpy.ndarray'>


In [14]:
values=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(values)
print(values.shape)  # 3 rows and 4 columns
print(values.ndim)  # Two dimensions

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [15]:

int=np.array([10,40,80,100])
print(int)
print(int.shape)
print(int.ndim)

[ 10  40  80 100]
(4,)
1


In [17]:
a=np.array([[10,20,30],[66,34,55],[235,456,678]])
print(a)
print(type(a))
print(a.shape)
print(a.ndim)

[[ 10  20  30]
 [ 66  34  55]
 [235 456 678]]
<class 'numpy.ndarray'>
(3, 3)
2


In [18]:
print(a[1][1])

34


In [19]:
print(a[2][1])

456


In [20]:
x=np.arange(1,20) # follow the n-1 concept
print(x)
print(x.shape)
print(x.ndim)
print(type(x))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(19,)
1
<class 'numpy.ndarray'>


In [21]:
y=np.arange(30,50)
print(y)
print(y.shape)
print(y.ndim)
print(type(y))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
(20,)
1
<class 'numpy.ndarray'>


In [25]:
# reshape
# converting 1d to 2d
x=np.arange(1,41).reshape(10,4)
print(x)
print(x.shape)
print(x.ndim)
print(x.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]]
(10, 4)
2
40


In [27]:
y=np.arange(1,61).reshape(10,6)
print(y)
print(y.shape)
print(y.ndim)
print(y.size)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
(10, 6)
2
60


In [30]:
print(y[8][1])

50


In [33]:
print(y[5][4])

35


In [36]:
# converting 1d to 3d
y=np.arange(1,61).reshape(5,2,6)
print(y)
print(y.shape)
print(y.ndim)
print(y.size)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
(5, 2, 6)
3
60


In [37]:
print(y[1][1][1])

20


In [38]:
print(y[3][1][3])

46


In [39]:
a=np.arange(1,10)
print(a)
print(type(a))
print(a.min())

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1


In [40]:
print(a.max())

9


In [42]:
z=np.array([[1,2,3],[6,9,10],[12,14,16]])
print(z)
z.argmax(axis=1)

[[ 1  2  3]
 [ 6  9 10]
 [12 14 16]]


array([2, 2, 2], dtype=int64)

In [43]:
z.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [11]:
#ravel

z=np.array([[1,2,3],[6,9,10],[12,14,16]])
print(z)
z.ravel()



[[ 1  2  3]
 [ 6  9 10]
 [12 14 16]]


array([ 1,  2,  3,  6,  9, 10, 12, 14, 16])

In [12]:
# transpose

z=np.array([[1,2,3],[6,9,10],[12,14,16]])
print(z)
z.T

[[ 1  2  3]
 [ 6  9 10]
 [12 14 16]]


array([[ 1,  6, 12],
       [ 2,  9, 14],
       [ 3, 10, 16]])

In [13]:
# # concatinate

a = np.array([[11,24,13] , [101,11,122] , [121,20,2]])

b = np.array([[1,2,3],[10,11,12],[99,98,200]])

c = np.concatenate((a,b))

print(c)

[[ 11  24  13]
 [101  11 122]
 [121  20   2]
 [  1   2   3]
 [ 10  11  12]
 [ 99  98 200]]
